### ISSUE TITLE
Does `tensorrt`  module is needed for c binding for inference ?

### ISSUE THREAD

**Issue by oak-tree** [tensorflow/tensorrt#100]
We compiled `tensorflow` with and without `tensorrt` for `jetson` (arm64). But now when I'm thinking on it, does `tensorrt` is actually needed for inference stage?

**Comment by ZhuoranLyu** [comment]
> We compiled `tensorflow` with and without `tensorrt` for `jetson` (arm64). But now when I'm thinking on it, does `tensorrt` is actually needed for inference stage?

Hi @oak-tree , would you plz tell me how to compile tftrt with tensorrt for C/C++ API? Thx!

**Comment by pooyadavoodi** [comment]
@oak-tree Yes, TensorRT is needed during inference.

**Comment by pooyadavoodi** [comment]
NVIDIA releases TensorFlow packages for Jetson platform: https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html

**Comment by pooyadavoodi** [comment]
If your original question was about the Python `tensorrt` module, I think that's not needed if you directly use the C API.

**Comment by pooyadavoodi** [comment]
Closing. Please reopen if the problem persists.
