### ISSUE TITLE
create_inference_graph() causing "placeholder tensor" issue

### ISSUE THREAD

**Issue by jtressle** [tensorflow/tensorrt#102]
Hi,

I'm running into the same issue as  https://github.com/tensorflow/tensorrt/issues/44 where using create_inference_graph() returns error "You must feed a value for placeholder tensor 'import/input_tensor' with dtype string and shape".  

I've had this happen with my own frozen graph, as well as the graph mentioned in #44 .

That issue has been closed, but there is no resolution.  What needs to be done?  

I'm running Tensorflow-GPU 1.14.0 on ubuntu 16 with Cuda 10.0.

Thanks in advance,

My error message:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'import/input_tensor' with dtype string and shape [?]
> 	 [[node import/input_tensor (defined at convert.py:19) ]]

**Comment by austingg** [comment]
PlaceHolder need an feed input, such as
sess.run([ouptut], feed_dict={'PlaceHoder name': image})

**Comment by pooyadavoodi** [comment]
Closing. Please feel free to re-open if you still have this problem.
