### ISSUE TITLE
TRT Conversion  from TF saves dictionary file in graph making the protobuf too large

### ISSUE THREAD

**Issue by damitkwr** [tensorflow/tensorrt#103]
Hi,

To produce take any model and add a 1GB or some large dictionary in the assets folder for a saved_model format. Run the TF-TRT conversion which will produce a protobuf file of size > 1GB or sometimes 2GB. If we then try to serve the model through TF-Serving or NVIDIA TRT Server then you will get this error:

`A protocol message was rejected because it was too big (more than 1073741824 bytes). To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.`

Can we specify the TF-TRT converter to not save the dictionary in the graph and load it when the model is loaded?

Thanks!

**Comment by pooyadavoodi** [comment]
We did some optimization in this PR: https://github.com/tensorflow/tensorflow/pull/30789

I don't think this is released yet in any version of TF.

**Comment by pooyadavoodi** [comment]
Closing. 
Please test with TF 1.15 (rc0 is released), and reopen if the problem persists.

**Comment by jeisinge** [comment]
FYI - we are still seeing this issue with converting a SavedModel.  Our Saved Model has assets and variables and converts into a single `saved_model.pb` that is 1.1 GB.

```sh
7.1M saved_model.pb

variables:
total 51M
5.4K variables.index
51M variables.data-00000-of-00001

assets:
total 1.3M
480 albert_config.json
537K 30k-clean.vocab
743K 30k-clean.model
```

This converts into:
```
1.1G saved_model.pb

variables:
total 0
```

**Comment by sanjoy** [comment]
CC @bixia1

**Comment by ericxsun** [comment]
I met the same problem on TensorFlow 2.4.1 + TensorRT 6.0.1 with bert fine-tuned model

```sh
4.0K	./bert_finetune_20210203/assets
9.5M	./bert_finetune_20210203/saved_model.pb
387M	./bert_finetune_20210203/variables
397M	./bert_finetune_20210203

4.0K	./bert_finetune_20210203_fp16/assets
1.1G	        ./bert_finetune_20210203/saved_model.pb
387M	./bert_finetune_20210203_fp16/variables
1.5G	./bert_finetune_20210203_fp16

4.0K	./bert_finetune_20210203_fp32/assets
1.1G	        ./bert_finetune_20210203_fp32/saved_model.pb
387M	./bert_finetune_20210203_fp32/variables
1.5G	./bert_finetune_20210203_fp32

```
