### ISSUE TITLE
when force_nms_cpu is true and use_trt is true, will be core dumped

### ISSUE THREAD

**Issue by mpjlu** [tensorflow/tensorrt#107]
Error message:
`2019-07-31 20:59:13.742585: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:730] Number of TensorRT candidate segments: 3
2019-07-31 20:59:13.807654: F tensorflow/core/util/device_name_utils.cc:92] Check failed: IsJobName(job) 
Aborted (core dumped)`

Tensorflow version: from 1.13.1 to the latest all have this issue.
TensorRT version:TensorRT-5.0.2.6
cuDNN: cudnn-10.0-linux-x64-v7.4.2.24.tar
OS: ubuntu 16.04
tensorflow/tensorrt version: from r1.13 to the master all have this issue
models: ssd_mobilenet_v1_coco,ssd_resnet50_v1_fpn and others

Change tensorrt/tftrt/examples/object_detection/graph_utils.py:98 as follows will fix this core dumped.
 98 #node.device = '/device:CPU:0'
 99             node.device = '/job:localhost/replica:0/task:0/device:CPU:0'

Will change this?

**Comment by pooyadavoodi** [comment]
Please use TF 1.14 or a more recent version. Many bugs especially related to NMS got fixed since then.

Closing. Please reopen if the problem persists.

**Comment by ynjiun** [comment]
using TF1.15 the above reported problem still exists. But @mpjlu suggestion seems fixed the problem:

> Change tensorrt/tftrt/examples/object_detection/graph_utils.py:98 as follows will fix this core dumped.
> 98 #node.device = '/device:CPU:0'
> 99 node.device = '/job:localhost/replica:0/task:0/device:CPU:0'
