### ISSUE TITLE
build_model need to be imported in tensorrt/tftrt/examples/object_detection/__init__.py

### ISSUE THREAD

**Issue by terryjx** [tensorflow/tensorrt#110]
It seemed that build_model need to also be imported together with download_model in tensorrt/tftrt/examples/object_detection/__init__.py, in order to run the object detection sample code. 

Otherwise, import Error will be thrown out.

**Comment by pooyadavoodi** [comment]
I believe this is fixed now. There were some changes in the function names.

Closing. Please reopen in case you still see the issue.

**Comment by suhyung-code42** [comment]
add "build_model" at 1st line of  __init__.py like below

from .object_detection import download_model, download_dataset, optimize_model, benchmark_model, build_model

**Comment by sgriset** [comment]
Did not work for me still get import error
