### ISSUE TITLE
download_model function call bug in "tensorrt/tftrt/examples/object_detection/object_detection.py"

### ISSUE THREAD

**Issue by terryjx** [tensorflow/tensorrt#111]
In the sample file, "tensorrt/tftrt/examples/object_detection/object_detection.py"

The following line seemed to need to be changed:
261    config_path, checkpoint_path = download_model(
262        model_name=model_name,
263        input_dir=input_dir,
264        output_dir=output_dir)

as

261    config_path, checkpoint_path = download_model(
262        model_name=model_name,
263        input_dir=None,
264        output_dir=input_dir)

Otherwise, the given sample script for Download would throw out file path error.

**Comment by pooyadavoodi** [comment]
I believe this is fixed now. There were some changes in the function names.
Closing. In case you still see the issue, I appreciate it if you make a PR with the fix.
