### ISSUE TITLE
No tensorrt model in win10 python3.5 and python3.6

### ISSUE THREAD

**Issue by scholarboss** [tensorflow/tensorrt#113]
Exause Me
I use tensorflow in windows10, python3.5 
when I do 
"import tensorflow.contrib.tensorrt as trt"
error appears:
ImportError: No module named 'tensorflow.contrib.tensorrt'

How can I get the tensorrt model in tensorflow for win10 ?

**Comment by ZhuoranLyu** [comment]
tftrt does not support win10 unless you compile from source

**Comment by pooyadavoodi** [comment]
This issue is tracked here: https://github.com/tensorflow/tensorflow/issues/23692
Closing.
