### ISSUE TITLE
Tensorflow 2.0 support for tf-trt examples

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/tensorrt#122]
Hi, I can see that there is a new experimental 2.0 branch being maintained for this repository. I wanted to know if there is some timeline by which the entire examples repository is planned to be ported to tf-2.0 or if it is going to be a completely community based effort on the chronological front.

**Comment by pooyadavoodi** [comment]
We are working on making examples for TF2.0 and improving the current ones. 

I think the image classification example in the experimental branch is in a reasonable shape. Please use it and let us know your opinion.

Any help from the community is appreciated. Thanks.
