### ISSUE TITLE
tensorrt  ie not enable

### ISSUE THREAD

**Issue by bleedingfight** [tensorflow/tensorrt#14]
I want to use tensorrt optimize my ssd models.but when I use the code like this:
```
from tftrt.examples.object_detection import optimize_model
import os
model_dir='/home/amax/tensorrt/models/ssd_mobilenet_v1_coco_2018_01_28'
config_path=os.path.join(model_dir,'pipeline.config')
checkpoint_path=os.path.join(model_dir,'model.ckpt')
frozen_graph = optimize_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    use_trt=True,
    precision_mode='FP16'
)

```
something like this:
```
Traceback (most recent call last):
  File "optimizer_model.py", line 10, in <module>
    precision_mode='FP16'
  File "/home/amax/tensorrt/tftrt/examples/object_detection/object_detection.py", line 352, in optimize_model
    minimum_segment_size=minimum_segment_size)
  File "/home/amax/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 153, in create_inference_graph
    int(msg[0]))
tensorflow.python.framework.errors_impl.FailedPreconditionError: TensorRT is not enabled!

```
my env:
- tensorflow1.10 source compiled
- python 3.5.5(Anaconda 4.2.0)
- Linux amax-Super-Server 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- tensorrt tar `/usr/local/TensorRT-5.0.2.6`
- cuda9.1 cudnn7.1.4

I have installed tensorrt and install python whl file.I guess compiled from tensorflow source without tensorrt.I have forget it,but i can from tensorflow.contrib import tensorrt.so I don't know where is the problem.I compile with tensorrt some msg like this:
```
TensorRT libraries found in one the following directories are not compatible with selected cuda and cudnn installations
/usr/local/TensorRT-5.0.2.6
/usr/local/TensorRT-5.0.2.6/lib
/usr/local/TensorRT-5.0.2.6/lib64

```
Have someone use tensorrt optimizer the frozen.pb file?

**Comment by pooyadavoodi** [comment]
You would need to enable TensorRT when you compile Tensorflow.

Also,  Tensorflow 1.10 is old. Could you try the latest version 1.13. There has been quite a lot of bug fixes since 1.10.

**Comment by bleedingfight** [comment]
@pooyadavoodi 
Can you tell me what cuda can support tensorflow?I just try clone tenorflow from github and try compile it.but something wrong.so I just compile old version fron least-1.10.
My env:
- tensorrt5.0.2.6
- cuda9.1
- cudnn7.1.4

**Comment by pooyadavoodi** [comment]
Both CUDA 9 and 10 work with TF.

You should report the Tensorflow compilation issues at tensorflow/tensorflow.
