### ISSUE TITLE
No module named 'tensorflow.python.compiler.tensorrt'

### ISSUE THREAD

**Issue by maurera** [tensorflow/tensorrt#153]
**Platform**: Tensorflow 2.0. Python 3.7. Testing on local windows machine with no GPU before deploying to AWS EC2 machine with GPU.

Apologies if this is a very simple question.

I'm trying to use TensorRT for the first time in order to speed up model predict time. The nvidia documentation: [2.2.4. TF-TRT 2.0 Workflow With A SavedModel](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#worflow-with-savedmodel) says to start by running:
```
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
```

When I do this, I get the error: **ModuleNotFoundError: No module named 'tensorflow.python.compiler.tensorrt'**. Is tensorrt still included with tensorflow? Do I need to install it separately?

**Comment by maurera** [comment]
Issue solved by running on GPU machine. tensorflow.python.compiler.tensorrt appears to be included in tensorflow-gpu, but not (standard cpu-only) tensorflow

**Comment by quelibrio** [comment]
Also worth mentioning https://forums.developer.nvidia.com/t/error-converting-tensorflow-model-to-tensorrt-on-windows-10/83892 its not supported on windows 10
