### ISSUE TITLE
how to export tensorrt int8 model with savedmodel format after calibration for tf-serving？

### ISSUE THREAD

**Issue by rankeey** [tensorflow/tensorrt#20]
as the latest doc shows, we can call create_inference_graph with parameter input_saved_model_dir and output_saved_model_dir to export a savedModel model.
If use int8 qutization，it seems that after create_inference_graph，we still need call calib_graph_to_infer_graph to export the final model and the result is a frozen model.
So...

1. Is it possible to export a savedModel int8 model after calibration for tf-serving?

2. If it is possible, is there any demo could be offered？

3. If it is impossible，when will it may be possible？

**Comment by MachineJeff** [comment]
I met the problem in #148
