### ISSUE TITLE
Tensorflow Serving on Jetson platform

### ISSUE THREAD

**Issue by Wheest** [tensorflow/tensorrt#232]
The [following guide](https://medium.com/tensorflow/optimizing-tensorflow-serving-performance-with-nvidia-tensorrt-6d8a2347869a) shows how it is possible to run TF-TRT with Tensorflow serving, which is a very useful deployment workflow.

However, I am trying to run on a Jetson platform, and can't seem to get a container image which works.  This [official container image](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-tensorflow) allows TF-TRT to be run on a Jetson device.

However, I cannot find a container for the Jetson platform that uses the Serving interface. 

Is there a way to do this?

**Comment by DEKHTIARJonathan** [comment]
@bixia1 question about TF Serving & Jetson

**Comment by bixia1** [comment]
@Wheest Is this what you are looking for https://hub.docker.com/r/helmuthva/jetson-xavier-tensorflow-serving ?

**Comment by Wheest** [comment]
Thanks for looking at this @bixia1.  

It could potentially do the job, however it's an old image for JetPack 4.2.1, rather than the latest JetPack 4.4.  The [original project repo](https://github.com/helmut-hoffer-von-ankershoffen/jetson/tree/master/workflow/deploy/tensorflow-serving) is very geared to k8s, so I'm having difficulty figuring out how to adapt it to my needs.

Someone on the NVidia forums suggested a modified version of the Trition Inference Server ([forum post](https://forums.developer.nvidia.com/t/running-a-tf-tensorrt-model-as-a-inference-server-on-the-xavier/165123)).  I'm following the process described just now, though will need to see if works.

**Comment by DEKHTIARJonathan** [comment]
Triton is the recommended approach supported by NVIDIA.
If you have issues with regards to Triton, please open an issue here: https://github.com/triton-inference-server/server

I'm closing this issue since it's not a TF-TRT issue.
