### ISSUE TITLE
The following error occurs when running tf1.14. 0. Please find the solution

### ISSUE THREAD

**Issue by YubinYuan** [tensorflow/tensorrt#276]
from tensorflow.compiler.tf2tensorrt.wrap_py_utils import is_tensorrt_enabled
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt.wrap_py_utils'

**Comment by DEKHTIARJonathan** [comment]
It's more than 2 years old, obviously some things will not work. This repository aims to support the latest version of TensorFlow.
