### ISSUE TITLE
Tensorflow Docker 2.7.0-gpu has incompatible TRT version 8.0.0

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorrt#282]
Setup tensorflow/tensorflow:2.7.0-gpu container
```
$ sudo docker run -it --name tf270 --gpus all tensorflow/tensorflow:2.7.0-gpu
```
Test TF/TRT
```
$ apt list --installed | grep infer

libnvinfer-plugin8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]
libnvinfer8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]


import tensorflow as tf
import tensorflow.compiler as tf_cc
tf_cc.tf2tensorrt._pywrap_py_utils.get_linked_tensorrt_version()

(7, 2, 2)
```
ok, installed TRT is 8.0.0 but Tensorflow was built and linked with TRT 7.2.2. Looks like nobody tested TensorRT with tensorflow/tensorflow:2.7.0-gpu image

BTW, tensorflow/tensorflow:2.6.1-gpu container works fine. (Cuda 11.2, TRT 7.2.2, TF 2.6.1)

**Comment by DEKHTIARJonathan** [comment]
We are not building these containers. Please report this issue on tensorflow/tensorflow and tag me and @bixia1 and @sanjoy
