### ISSUE TITLE
why the run function parameter run_calibration was never used?

### ISSUE THREAD

**Issue by lutianfei** [tensorflow/tensorrt#32]
Hello, I am very curious that why the run_calibration parameter in the run method was never used?
So, I'm interested to see if the calibration function really works, especially if I switch to a different model

**Comment by pooyadavoodi** [comment]
Thanks for filing the issue. We need to remove `run_calibration` argument. 
It was only used to detect which files to read which wasn't a good way. It was used before when `run` was expecting `data_dir`, but now it expects `data_files`. 

Calibration has been tested with many image classification models and it works: https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html#verified-models

**Comment by pooyadavoodi** [comment]
Removed the redundant argument. 

@lutianfei Thanks for reporting this.
