### ISSUE TITLE
map does not match the numbers in models project

### ISSUE THREAD

**Issue by lbingbing** [tensorflow/tensorrt#33]
1. download the project and add project root to $PYTHONPATH.
2. I add a line to bypass optimization step:
```
diff --git a/tftrt/examples/object_detection/object_detection.py b/tftrt/examples/object_detection/object_detection.py
index 0d3528c..05b6cd7 100644
--- a/tftrt/examples/object_detection/object_detection.py
+++ b/tftrt/examples/object_detection/object_detection.py
@@ -327,6 +327,7 @@ def optimize_model(config_path,
     frozen_graph = tf.GraphDef()
     with open(frozen_graph_path, 'rb') as f:
         frozen_graph.ParseFromString(f.read())
+    return frozen_graph

     # apply graph modifications
     if force_nms_cpu:
```
3. my config file ssd_inception_v2_coco.json
```
{
  "source_model": {
    "model_name": "ssd_inception_v2_coco",
    "output_dir": "models"
  },
  "optimization_config": {},
  "benchmark_config": {
    "images_dir": "val2014",
    "annotation_path": "instances_minival2014.json",
    "batch_size": 1,
    "num_images": 100000,
    "output_path": "ssd_inception_v2_coco_trt_fp16.json"
  },
  "assertions": [
    "statistics['map'] > (0.268 - 0.005)"
  ]
}
```
instances_minival2014.json is from https://dl.dropboxusercontent.com/s/o43o90bna78omob/instances_minival2014.json.zip?dl=0
4. then run
python -m tftrt.examples.object_detection.test ssd_inception_v2_coco.json
5. result
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.278
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.401
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.306
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.027
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.202
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.634
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.240
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.307
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.308
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.035
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.232
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.695
mkdir: cannot create directory ‘’: No such file or directory
{
    "avg_latency_ms": 44.6612452507019,
    "avg_throughput_fps": 22.39077738174539,
    "map": 0.2776660805925762
}

this result does NOT match the number here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

Is there any official evaluation numbers for this tensorrt project?

**Comment by pooyadavoodi** [comment]
You are getting better mAP (0.27 vs. 0.24).
Could be due to using minival instead of val?

As a separate note, you are not using TF-TRT because your optimization config is empty.
You would need something like this:

```
  "optimization_config": {
    "use_trt": true,
    "precision_mode": "FP16",
    "max_batch_size": 1
  }
```

**Comment by pooyadavoodi** [comment]
The difference could be also because that table from tensorflow/models is kind of old. Perhaps if you try to reproduce those numbers, you get different results.

**Comment by lbingbing** [comment]
> You are getting better mAP (0.27 vs. 0.24).
> Could be due to using minival instead of val?
> 
> As a separate note, you are not using TF-TRT because your optimization config is empty.
> You would need something like this:
> 
> ```
>   "optimization_config": {
>     "use_trt": true,
>     "precision_mode": "FP16",
>     "max_batch_size": 1
>   }
> ```
I'm using 2014 minival according to this issue:
https://github.com/tensorflow/models/issues/6261

I emptied optimization config because I want to see result of origin model without fp16 optimization.

**Comment by lbingbing** [comment]
> The difference could be also because that table from tensorflow/models is kind of old. Perhaps if you try to reproduce those numbers, you get different results.

Thanks. Maybe it is the reason.

**Comment by lbingbing** [comment]
> You are getting better mAP (0.27 vs. 0.24).
> Could be due to using minival instead of val?
> 
> As a separate note, you are not using TF-TRT because your optimization config is empty.
> You would need something like this:
> 
> ```
>   "optimization_config": {
>     "use_trt": true,
>     "precision_mode": "FP16",
>     "max_batch_size": 1
>   }
> ```

I just tried val2014 (40k+ images) without fp16 opt config and still got map of 27.5

**Comment by pooyadavoodi** [comment]
@lbingbing did you try to repro the mAP from that table using the tensorflow/models scripts?
I feel those numbers are old and not reproducible by the uploaded models.
