### ISSUE TITLE
Some operations not converted, but stated as supported in TF-TRT user guide.

### ISSUE THREAD

**Issue by FeiZhu** [tensorflow/tensorrt#63]
I'm using TF-TRT to convert my model. The conversion is successful, but inference runs slower after conversion. While trying to figure out what goes wrong, I notice that some operations are not converted, which are however stated as supported in TF-TRT user guide.

The corresponding log is: "*There are 111 ops of 18 different types in the graph that are not converted to TensorRT: ExpandDims, Reshape, Mul, DataFormatVecPermute, Unpack, MirrorPad, Placeholder, Tile, Cast, NoOp, Elu, Pack, ResizeNearestNeighbor, Shape, StridedSlice, Identity, GreaterEqual, Select, (For more information see https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html#support-ops)*"

The supported ops section in user guide is: https://docs.nvidia.com/deeplearning/dgx/tf-trt-user-guide/index.html#usingtftrt. For instance, ExpandDims, Reshape, and Mul are clearly stated as supported.

I'm not sure whether this is the reason to the performance decrease, but this is probably an issue. I tried changing the fraction of memory that tensorRT could use, the max batch size, neither of them really helped.

BTW, I'm using TensorFlow-gpu 1.13.1 installed via pip, TensorRT-5.0.2.6, and the GPU is RTX 2080.

**Comment by pooyadavoodi** [comment]
Sorry for the late reply.

The log that says `There are 111 ops of 18 different types in the graph that are not converted to TensorRT: ...` lists the ops that were not converted. Some of those ops could be supported by TF-TRT in the general sense, but not for every possible input types or shapes.

I'd like to look into the performance issue you see, but I need your model and script for repro.

Which precision did you use? FP32, FP16, INT8?

A very important optimization for detection models is using the new TF op called CombinedNonMaxSuppression. We get a large speedup just with that.

**Comment by SimsGautam** [comment]
@pooyadavoodi Is there any documentation on the speedups for detection models?

Only benchmark I've found is ~3x speedup with TRT + FP16 on `SSD MobileNet V1`. Does that benchmark include the`CombinedNonMaxSuppression` change?

Curious if there are speedup benchmarks available for some other supported detection models (e.g. `SSD Resnet50 FPN`, `Faster RCNN`). Thanks!

**Comment by FeiZhu** [comment]
@pooyadavoodi  Thanks for the reply. 

> Some of those ops could be supported by TF-TRT in the general sense, but not for every possible input types or shapes.

It's very helpful. Now I see why the log says some ops are not converted.

**Comment by Sreerag-ibtl** [comment]
Hi, facing the exact same issue. I am using TF2.3  in Jetson Nano. Dynamic batch shapes are used. Some ops such as Reshape are not converted.
