### ISSUE TITLE
Unable to run bigger batch sizes

### ISSUE THREAD

**Issue by nikithamuddireddy** [tensorflow/tensorrt#66]
Hi,

I am unable to run batchsizes larger than 1000. Has anyone else faced the same problem?

**Comment by pooyadavoodi** [comment]
What happens when you run it?
Do you have the log and the script for repro?

It depends on the model.
We have used larger batch sizes for some models.

**Comment by pooyadavoodi** [comment]
Closing. Please feel free to reopen if the problems persists.
