### ISSUE TITLE
TensorRT with multiple models crash down. 

### ISSUE THREAD

**Issue by Mengjintao** [tensorflow/tensorrt#68]
The error message is: 
ValueError: Cannot add function 'my_trt_op_1_native_segment' because a different function with the same name already exists.

The code (I put it here: https://github.com/Mengjintao/TF_TensorRT_test) will generate the above error message. But occasionally it may works fine. 

I have no idea why this happens when I use multiple models with TF over TensorRT.  Our code TF over CUDNN works fine. 

Jintao Meng
2019.5.15

**Comment by Mengjintao** [comment]
I use two totally different models, the code with TF-TRT works fine. 
If I use two same models, the code with  TF-TRT occasionally crashes.  
If I use two models with similar ops, the code with  TF-TRT crashes definitely.

**Comment by pooyadavoodi** [comment]
@Mengjintao Could you try to import trt_engine1 and trt_engine2 into two different tf.Graph.

You can enclose your import in something like this:

```
g = tf.Graph()
with g.as_default():
    import ...
```

**Comment by pooyadavoodi** [comment]
Closing. Please feel free to reopen if the problems persists.

**Comment by prnvjb** [comment]
Hey @pooyadavoodi 
Could you give please explain that mechanism?
Thanks!
