### ISSUE TITLE
does tf-trt support dynamic shape inputs used for image segmentation models ?

### ISSUE THREAD

**Issue by argman** [tensorflow/tensorrt#75]
and are there any c++ examples using tf-trt?

**Comment by chong-lee** [comment]
same question

**Comment by pooyadavoodi** [comment]
There are multiple issues related to dynamic shapes.

- If the input graph has unknown shapes, the TF-TRT dynamic mode is able to handle them. Set `is_dynamic_op=True` in the API.
- Certain shape manipulations are not supported. One example is tf.Shape. Another example is reshaping the batch dimension. We are working on extending the support with the next release of TensorRT.

**Comment by pooyadavoodi** [comment]
Unfortunately we don't have a C++ example yet. We are planning to make one.

**Comment by argman** [comment]
@pooyadavoodi tks, i will try and update if it works

**Comment by pooyadavoodi** [comment]
Closing. Please reopen in case the issue remains.

**Comment by vinhngx** [comment]
@argman we've now got a TF-TRT C++ example here https://github.com/tensorflow/tensorrt/tree/r1.14%2B/tftrt/examples/cpp/image-classification
