### ISSUE TITLE
TRT inference with graph trained in a "FIFO queue" style  

### ISSUE THREAD

**Issue by zguo008** [tensorflow/tensorrt#77]
Hi, 

Bear with me if I ask this question in the wrong place.

I am trying to optimize a tf model with TRT. I have encountered some trouble:

1.Original model is trained in a FIFO queue style. So basically [image, label, existence] are pushed into a queue and this bunch of data is dequeued before forward propagation.

2.I loaded the trained checkpoint and freeze it to a frozen graph. Frozen graph is optimized  using trt_create_inference_graph().

3. I want to use get_tenor_by_name to get the input and 2 outputs and use sess.run() to make a prediction. And this fails. I have printed out the nodes and found the pre-processing nodes are removed and only a queue node remains like this:

name: "prefetch_queue/fifo_queue"
op: "FIFOQueueV2"
attr {
  key: "capacity"
  value {
    i: 4
  }
}
attr {
  key: "component_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_INT32
      type: DT_FLOAT
    }
  }
}
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "shapes"
  value {
    list {
      shape {
        dim {
          size: 4
        }
        dim {
          size: 256
        }
        dim {
          size: 512
        }
        dim {
          size: 3
        }
      }
      shape {
        dim {
          size: 4
        }
        dim {
          size: 256
        }
        dim {
          size: 512
        }
      }
      shape {
        dim {
          size: 4
        }
        dim {
          size: 4
        }
      }
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}

I wanted to replace the queue with a placeholder (?,256,512,3) and run the model based on the optimized graph but there is no luck so far. 
(Failed try:
#freezed_input_tensor has name INPUT+':0'
output1 =   get_tensor_by_name(output1+':0')
output2 =   get_tensor_by_name(output2+':0')
my_input_tensor = tf.placeholder(dtype=tf.float32, shape=[1,256,512,3], name='my_input')
tf.import_graph_def(trt_graph, input_map = {INPUT + ':0':my_input_tensor},name='') 
sess.run(output1,output2, feed_dict:{my_input_tensor : my_image}) -->>fails at this step)

As the code provided only shows how inference can be optimised, could you please show how the model is trained as well?

Also, has anybody encountered the situation where I want to feed a placeholder to a graph trained with a FIFO queue?

Best,

ZX

**Comment by pooyadavoodi** [comment]
Are the queue ops inside the graph you give to TF-TRT API?

@aaroey Any idea how the queue ops can be replaced by a placeholder in this case?

**Comment by aaroey** [comment]
@zguo008 could you provide a minimum graph that can reproduce the error with your code? I'm curious what was failing during the `sess.run()` step.

**Comment by pooyadavoodi** [comment]
Closing. Please reopen in case the issue remains.
