### ISSUE TITLE
Does not work on FPN model?

### ISSUE THREAD

**Issue by JunweiLiang** [tensorflow/tensorrt#80]
Hi,

I have a self-implemented object detection model here:

Basically it is a Resnet101 + FPN + Faster RCNN model.

I used [this code](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/tensorrt_optimize.py) with [these commands](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/SPEED.md) to convert the frozen graph and it reports no error:

graph_size(MB)(native_tf): 245.5
graph_size(MB)(trt): 245.0
num_nodes(native_tf): 5125
num_nodes(tftrt_total): 2618
num_nodes(trt_only): 47
time(s) (trt_conversion): 19.7020

Then during inference, I got this error:

InternalError (see above for traceback): Native FunctionDef fpn/upsample_lat5/Tensordot/TRTEngineOp_39_native_segment can't be found in function library
         [[node model_0/fpn/upsample_lat5/Tensordot/TRTEngineOp_39 (defined at /home/junweil/object_detection/script/tf_mrcnn/models.py:147) ]]
         [[{{node model_0/fastrcnn_predictions/map/while/body/_1/GatherV2_1}}]]

Could you give me some pointers? Thanks!

**Comment by JunweiLiang** [comment]
https://github.com/JunweiLiang/Object_Detection_Tracking

**Comment by pooyadavoodi** [comment]
@JunweiLiang Looks like you are using `is_dynamic_op=False`. Could you change that to `True` and retry.

**Comment by JunweiLiang** [comment]
Thanks. It works now on TF v1.14.0 (is_dynamic_op=True still fails on TF v1.13). However, it seems that there is no significant speed improvement when I just use FP32 and FP16 mode.

**Comment by PetreanuAndi** [comment]
Hello :D I've tried using your code and the tutorials provided on the official resource page, and it seems like the conversion brings ABSOLUTELY NO optimization improvement. (regardless of precision mode)

I'm using an SSD with FPN architecture, pretrained from COCO.

The output of the script looks like this : 
(notice 0 tfrt nodes)

2019-08-06 13:07:14.320322: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-08-06 13:07:14.320482: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 2836 nodes (-1660), 4183 edges (-1854), time = 603.806ms.
2019-08-06 13:07:14.320498: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 2880 nodes (44), 4255 edges (72), time = 175.896ms.
2019-08-06 13:07:14.320549: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 2880 nodes (0), 4255 edges (0), time = 196.966ms.
graph_size(MB)(native_tf): 123.3
graph_size(MB)(trt): 123.2
num_nodes(native_tf): 4496
num_nodes(tftrt_total): 2880
**num_nodes(trt_only): 0**
time(s) (trt_conversion): 2.9548

I was expecting at least a smaller memory footprint in GPU, but that has not happened, and the graph size is basically equal to previous non-trt (123.3 ~= 123.2MB)

Any suggestions?
Is there an object detection architecture out there that plays well with TRT? (and has the same type of trade-off as SSD+FPN)?

Thank you!

**Comment by austingg** [comment]
@PetreanuAndi  `num_nodes(trt_only):0 ` means you haven't used tftrt correctly.

**Comment by PetreanuAndi** [comment]
@austingg , i used TFRT correctly, basically just ran the provided code with my custom outputs :)
It was just a matter of finding the right setup (tensorflow version / cuda / cudnn)
It seems that SSD + FPN will only be optimised in a nightly tensorflow 1.15 build.

After installing that particular setup, and using the same exact code i had used before, to convert the .pb file, i now have >0 trt_only nodes and an increase in speed of about 30% (on 1080Ti, not fully supporting FP16) speed increase is about 50% when switching to 2060S hardware, with 430.40 driver and Cuda 10.1

FP32 will actually work slower than non-optimised.

**Comment by aif2017** [comment]
> 
> 
> @austingg , i used TFRT correctly, basically just ran the provided code with my custom outputs :)
> It was just a matter of finding the right setup (tensorflow version / cuda / cudnn)
> It seems that SSD + FPN will only be optimised in a nightly tensorflow 1.15 build.
> 
> After installing that particular setup, and using the same exact code i had used before, to convert the .pb file, i now have >0 trt_only nodes and an increase in speed of about 30% (on 1080Ti, not fully supporting FP16) speed increase is about 50% when switching to 2060S hardware, with 430.40 driver and Cuda 10.1
> 
> FP32 will actually work slower than non-optimised.

could you please explain your steps more?

**Comment by zychen2016** [comment]
could you please explain your steps more? @PetreanuAndi
