### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TrtGraphConverter'

### ISSUE THREAD

**Issue by yiyele** [tensorflow/tensorrt#81]
when i use example,i got an error,should i update my tf to 14 or 13?

**Comment by huaifeng1993** [comment]
I meet the same problem.The version of my tensorflow is 1.13.1

**Comment by mankeyboy** [comment]
Tensorflow has changed their API from 1.14 onwards and the current code versions have incorporated those modifications. You can either use the tf-nightly-gpu builds which now give 1.14 or move to an older commit which uses the older API.

**Comment by pooyadavoodi** [comment]
In this repo, we have a [branch for TF1.13](https://github.com/tensorflow/tensorrt/tree/r1.13) which is basically the old scripts. We are not going to update them except for certain bug fixes.

**Comment by pooyadavoodi** [comment]
Closing. Please reopen in case the issue remains.
