### ISSUE TITLE
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor

### ISSUE THREAD

**Issue by ThiagoMateo** [tensorflow/tensorrt#83]
HI everyone. I try to optimize my frozen model, but i got below error. I dont know how to fix.
error:
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'impor
t/inputs' with dtype float and shape [?,320,320,3]                                                 
         [[{{node import/inputs}} = Placeholder[dtype=DT_FLOAT, shape=[?,320,320,3], _device="/job:
localhost/replica:0/task:0/device:GPU:0"]()]]                                                      

```
My optimize code:
```
# Import TensorFlow and TensorRT                                           
import tensorflow as tf                                                    
import tensorflow.contrib.tensorrt as trt                                  
# Inference with TF-TRT frozen graph workflow:                             
graph = tf.Graph()                                                         
with graph.as_default():                                                   
    with tf.Session() as sess:                                             
        # First deserialize your frozen graph:                             
        with tf.gfile.GFile('frozen_darknet_yolov3_model.pb', 'rb') as f:  
            graph_def = tf.GraphDef()                                      
            graph_def.ParseFromString(f.read())                            
        # Now you can create a TensorRT inference graph from your          
        # frozen graph:                                                    
        trt_graph = trt.create_inference_graph(                            
            input_graph_def=graph_def,                                     
            outputs=['output_boxes'],                                      
            max_batch_size= 8 ,                                            
            max_workspace_size_bytes=24,                                   
            precision_mode="FP16")                                         
        # Import the TensorRT graph into a new graph and run:              
        output_node = tf.import_graph_def(                                 
            trt_graph,                                                     
            return_elements=["output_boxes"])                              
        sess.run(output_node)                                              

```

**Comment by pooyadavoodi** [comment]
You probably need to set `is_dynamic_op=True` in the API.

This explains the difference: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#static-dynamic-mode

**Comment by pooyadavoodi** [comment]
Closing. Please reopen if the problem persists.

**Comment by sonal-511** [comment]
I am still facing the same issue.I have stated my code below

with tf.Session() as sess:
    # First deserialize your frozen graph:
    with tf.gfile.GFile("/content/drive/My Drive/kaam/faster_rcnn_resnet101_kitti_2018_01_28/frozen_inference_graph.pb", 'rb') as f:
        frozen_graph = tf.GraphDef()
        frozen_graph.ParseFromString(f.read())
    # Now you can create a TensorRT inference graph from your
    # frozen graph:
    converter = trt.TrtGraphConverter(
	    input_graph_def=frozen_graph,
      is_dynamic_op=True,
      
	    nodes_blacklist=['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections']) #output nodes
    trt_graph = converter.convert()
    # Import the TensorRT graph into a new graph and run:
    output_node = tf.import_graph_def(
        trt_graph,
        return_elements=['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'])
    sess.run(output_node)

**Comment by sonal-511** [comment]
**the issue still remains**

with tf.Session() as sess:
    # First deserialize your frozen graph:
    with tf.gfile.GFile("/content/drive/My Drive/kaam/faster_rcnn_resnet101_kitti_2018_01_28/frozen_inference_graph.pb", 'rb') as f:
        frozen_graph = tf.GraphDef()
        frozen_graph.ParseFromString(f.read())
    # Now you can create a TensorRT inference graph from your
    # frozen graph:
    converter = trt.TrtGraphConverter(
	    input_graph_def=frozen_graph,
      is_dynamic_op=True,
     nodes_blacklist=['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections']) #output nodes
    trt_graph = converter.convert()
    # Import the TensorRT graph into a new graph and run:
    output_node = tf.import_graph_def(
        trt_graph,
        return_elements=['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'])
    sess.run(output_node)

**the output is-**

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'import_4/image_tensor' with dtype uint8 and shape [?,?,?,3]
	 [[{{node import_4/image_tensor}}]]
	 [[import_4/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/strided_slice/_175]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'import_4/image_tensor' with dtype uint8 and shape [?,?,?,3]
	 [[{{node import_4/image_tensor}}]]
0 successful operations.
0 derived errors ignored.
