### ISSUE TITLE
No module named compiler.tensorrt  

### ISSUE THREAD

**Issue by xxllp** [tensorflow/tensorrt#84]
> from tftrt.examples.object_detection import download_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tftrt/examples/object_detection/__init__.py", line 18, in <module>
    from .object_detection import download_model, download_dataset, optimize_model, benchmark_model
  File "tftrt/examples/object_detection/object_detection.py", line 22, in <module>
    from tensorflow.python.compiler.tensorrt import trt_convert as trt
ImportError: No module named compiler.tensorrt

**Comment by xxllp** [comment]
I test on tf 1.10

**Comment by Eloring** [comment]
I got the same issue on tf 1.13. What's the lowest version including compiler.tensorrt?

**Comment by akhilvasvani** [comment]
From TensorFlow 1.14.1, did the switch occur. When I say switch I mean:

```import tensorflow.contrib.tensorrt as trt ``` (used in ≤ TensorFlow 1.13.1 ) -->
```from tensorflow.python.compiler.tensorrt import trt``` (TensorFlow ≥ 1.14.1)

**Comment by xxllp** [comment]
thanks , akhilvasvani

**Comment by caspainde** [comment]
@akhilvasvani I am using tensorflow 1.14.0, how can I import trt?

**Comment by akhilvasvani** [comment]
from tensorflow.python.compiler.tensorrt import trt

**Comment by caspainde** [comment]
@akhilvasvani Thanks! I forgot to mention that the deployed platform is TX2 but the train platform is windows. I find in doc from Nvidia that tensorrt does not support python on windows, I can't test it with tensorrt on windows right?

**Comment by akhilvasvani** [comment]
I think in general this is true, but some have found a way to get it working, which leads to two possibilities: 

1) Easy Route: Use Google Colabs to test instead of Windows for TensorRT. It is cross platform and you will be able to run anything

2) Hard Route: Build TensorFlow using Bazel on Windows and then run TensorRT. This [post](https://github.com/tensorflow/tensorflow/issues/23692) mentions on how to proceed. Personally, I have not undertaken this route (I use Ubuntu), so I cannot comment on this approach. It is definitely an uphill battle, but if you are able to get it working please do share on how you proceeded because that would help a lot of people

**Comment by fxl-fxl** [comment]
> From TensorFlow 1.14.1, did the switch occur. When I say switch I mean:
> 
> `import tensorflow.contrib.tensorrt as trt ` (used in ≤ TensorFlow 1.13.1 ) -->
> `from tensorflow.python.compiler.tensorrt import trt` (TensorFlow ≥ 1.14.1)
> 
> Hope this helps

thanks for the help

**Comment by ZhuoranLyu** [comment]
> @caspainde: I think in general this is true, but some have found a way to get it working, which leads to two possibilities:
> 
> 1. Easy Route: Use Google Colabs to test instead of Windows for TensorRT. It is cross platform and you will be able to run anything
> 2. Hard Route: Build TensorFlow using Bazel on Windows and then run TensorRT. This [post](https://github.com/tensorflow/tensorflow/issues/23692) mentions on how to proceed. Personally, I have not undertaken this route (I use Ubuntu), so I cannot comment on this approach. It is definitely an uphill battle, but if you are able to get it working please do share on how you proceeded because that would help a lot of people

The tensorrt optimized model is platform dependent. I am struggling with how to run tftrt on windows.

**Comment by pooyadavoodi** [comment]
Please track the Windows issue here: https://github.com/tensorflow/tensorflow/issues/23692

Closing.

**Comment by Spidy20** [comment]
Guys if you are doing openpose then just comment this line
`import tensorflow.contrib.tensorrt as trt`
in `tf_pose/estimator.py`

**Comment by ncthong** [comment]
@Spidy20 i'm doing openpose and this issue has not been resolved. Can you help me?

**Comment by Spidy20** [comment]
Remove that import line, it doesn't do anything in code.

**Comment by quelibrio** [comment]
Also worth mentioning https://forums.developer.nvidia.com/t/error-converting-tensorflow-model-to-tensorrt-on-windows-10/83892 its not supported on windows 10

**Comment by vivva** [comment]
I am also doing openpose. I tried both, but it still have some wrong  when my tensorflow is 1.4.1. What can I do?

> 
from tensorflow.python.compiler.tensorrt import trt

ModuleNotFoundError: No module named 'tensorflow.python.compiler'

> 
import tensorflow.contrib.tensorrt as trt

ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'

**Comment by Spidy20** [comment]
Put that import line into a comment. that's all.

**Comment by vivva** [comment]
I just creat a new environment when I change the tensorflow from 1.4.1 to 1.14 and it works! Thank you very much !

**Comment by Spidy20** [comment]
Glad to hear it!

**Comment by 1arctic** [comment]
version=2.4.0，it doesn't work

**Comment by Spidy20** [comment]
@1arctic  go with the TF 1.x. and try once again, can you tell me what is the error which you are getting?

**Comment by azarkiel** [comment]
tensorflow=2.5.0
It doesn't work
