### ISSUE TITLE
TensorRT Mistmatch

### ISSUE THREAD

**Issue by akhilvasvani** [tensorflow/tensorrt#85]
OS and version: Ubuntu 18.04
GPU type: NVIDIA GeForce GTX 1080 Ti Founder's Edition
nvidia driver version: 418.56
CUDA version: 10.0
cuDNN version: 7.4.1
Python version: 3.6.7
TensorFlow version:1.13.1
TensorRT version: 5.1.2

Following the instructions per the TensorRT manual, I used the frozen model to implement Tensorflow-RT:
```
import tensorflow.contrib.tensorrt as trt

trt_graph = trt.create_inference_graph(input_graph_def=frozen_graph, outputs=[out.op.name for out in model.outputs], max_batch_size=1,max_workspace_size_bytes=2 << 20, precision_mode="fp16")
tf.train.write_graph(trt_graph, "model", "tfrt_model.pb", as_text=False)
```

However, then I get the error: 
```
WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.2. Things may not work.
```

What exactly is not lining up? Is my CUDA version too low? Is my cuDNN too low as well? Does it need to be upgraded to 10.1? Or should I downgrade my TensorRT? Am I missing something? Any help would be greatly appreciated.

**Comment by pooyadavoodi** [comment]
The version of your TensorRT is 5.1.2 while the version of the TensorRT used to build TF is 5.0.2. They don't match.

Where do you download your TF from?
The pip packages that Google has uploaded to PyPI are build with TensorRT 5.0.
If you want to use TensorRT 5.1, you would have to either use [NVIDIA containers](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html) or build TF yourself.

**Comment by akhilvasvani** [comment]
Ok, I will rebuild my TensorFlow using Bazel. Thanks so much

**Comment by pooyadavoodi** [comment]
Note that TensorRT follows https://semver.org/

Loading 5.1.2 instead of 5.0.2 is probably fine. That's just a warning message for your information.
