### ISSUE TITLE
InvalidArgumentError: Expected image (JPEG, PNG, or GIF)

### ISSUE THREAD

**Issue by infichen** [tensorflow/tensorrt#94]
I run Image classification example but it taks errors:
![image](https://user-images.githubusercontent.com/13826604/60967668-cf76f600-a34d-11e9-935a-eace6288229a.png)

  the ImageNet validation data like this，generate with the  build_imagenet_data/build_imagenet_data.py
![image](https://user-images.githubusercontent.com/13826604/60967779-0c42ed00-a34e-11e9-8e4f-641a3ae0332d.png)

**Comment by infichen** [comment]
Can anyone help me?

**Comment by pooyadavoodi** [comment]
Could you post the command you use to run the script?

**Comment by xgu3** [comment]
@infichen I just met same problem, how did you solve it?

**Comment by infichen** [comment]
> @infichen I just met same problem, how did you solve it?

the validation dateset convert to TFRecords has problem, modify build_imagenet_data.py like this can solve the problem.
![image](https://user-images.githubusercontent.com/13826604/63138281-7feeae80-c00c-11e9-9388-6913943559a3.png)

**Comment by xgu3** [comment]
It works, thank you very much, @infichen
