### ISSUE TITLE
0 trt_only Nodes for ssd_mobilenet_v1_coco

### ISSUE THREAD

**Issue by nseidl** [tensorflow/tensorrt#96]
I followed the documentation steps [here](https://github.com/tensorflow/tensorrt/blob/master/tftrt/examples/object_detection/README.md). 

(another issue is that the current documentation provides a `checkpoint_path` to `optimize_model`, but `optimize_model` only takes a frozen graph. I fixed this by loading the frozen graph in and passing it to `optimize_model`.

This is the output from the `optimize_model` call (following the example):

```
graph_size(MB)(native_tf): 27.8
graph_size(MB)(trt): 27.8
num_nodes(native_tf): 6063
num_nodes(tftrt_total): 6047
num_nodes(trt_only): 0
time(s) (trt_conversion): 4.6702
```

**Is this expected? Why are there zero trt_only nodes?**

**Comment by pooyadavoodi** [comment]
Thanks for pointing our the documentation issue. I just fixed that. It was outdated.

**Comment by pooyadavoodi** [comment]
Having 0 TRT nodes is unexpected. 
Could you post how you run the example, plus the version of TF and TRT you are using?

**Comment by YTLin26** [comment]
I download the latest version of tftrt.
But, I still got the same problems.
Then, my version of TF is 1.14.
The version of TRT is 0.0

**Comment by austingg** [comment]
@YTLin26  you can use tf-trt only build tensorflow from source with tensorrt enable or use nvidia tensorflow docker.

**Comment by aif2017** [comment]
> 
> 
> @YTLin26 you can use tf-trt only build tensorflow from source with tensorrt enable or use nvidia tensorflow docker.

is there step by step tutorial to do this? I have nvidia-docker and also nvidia tensorrt . now what can I do?

**Comment by pooyadavoodi** [comment]
Could you post the full log of TF.

It would be good if you can post scripts or command lines you use.

**Comment by YTLin26** [comment]
> @YTLin26 you can use tf-trt only build tensorflow from source with tensorrt enable or use nvidia tensorflow docker.

Thanks for your response. You are right, I can convert the detection model (faster-rcnn-resnet50) in nvidia tensorflow docker successfully.
But Is there any way can convert the converted model (tftrt_faster-rcnn-resnet50) to plan file?
Because I want to run this model on tensorRT environment. Anyone has succeeded?

**Comment by pooyadavoodi** [comment]
Each TRTEngineOp in the graph can be converted to a plan file: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#tensorrt-plan

So if you have multiple TRTEngineOp in the graph, each of those needs to be converted to a plan file separately. The ideal would be if your whole graph gets converted to a single TRTEngineOp.

**Comment by pooyadavoodi** [comment]
Closing. Please reopen in case you still see the issue.

**Comment by Programmerwyl** [comment]
I found that the reason why there was no TRTEngineOp was not the code, but the hardware platform. I ran the same code on PC with mobilenet_v2. After optimization, TRTEngineOp was 0 with 426 total nodes, but I ran it on tx2 with only 3 nodes, which was much faster
