### ISSUE TITLE
inference with tf-trt

### ISSUE THREAD

**Issue by chong-lee** [tensorflow/tensorrt#99]
During convert frozen model to tf-trt optimized model, i have some question:
1. I convert model use tensorrt function create_inference_graph, after that i print graph's node name and node op, and found there is no op named 'TRTEngineOp', is this means the optimize failed? code like this:
```       
with tf.Session() as sess:
    # read a frozen model:
    with tf.gfile.GFile(sys.argv[1], 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    trt_graph = trt.create_inference_graph(
        input_graph_def = graph_def,
        outputs = outstr,
        max_batch_size = 1,
        max_workspace_size_bytes = (1<<20),
        precision_mode = "FP32")
    with open('trt.op', 'w') as fw:
        for n in trt_graph.node:
            fw.write(n.op+'\t'+n.name+'\n')
    constant_graph = graph_util.convert_variables_to_constants(sess, trt_graph, outstr)
    with tf.gfile.GFile(sys.argv[2], "wb") as f:
        f.write(constant_graph.SerializeToString())
```
2. Can i save the tf-trt optimized model(like .pb) and run the optimized model with cpp for online inference?
3. Is there a way or example for using tf-trt with cpp for model inference, i have already compile tensorflow with tensorrt from source, but i can't find any demo or api for cpp inference using tf-trt.
Thanks.

**Comment by ZhuoranLyu** [comment]
@chong-lee Hi, did u fix this problem? Or did u find the answers to these questions?

**Comment by chong-lee** [comment]
According to my experience. 1. model optimized directly with the tf default installation package does not have 'TRTEngineOp', which means that the optimization is not successful. According to NVIDIA's official documentation, you need to use TensorFlow container or compile TensorFlow with TensorRT through source code. The latter one I tried is ok. I can save the optimized model as pb, and then use CPP to inference online. Through experiments, QPS of the classification model (inception_v3) FP16 is increased by 3 times. However, the OCR model, because the input is not fixed, the optimization is not successful.
我想我大概知道答案，1、直接用tf默认安装包优化的模型是没有'TRTEngineOp'的，也就意味着优化不成功。根据NVIDIA的官方文档，需要通过TensorFlow container或者通过源码编译TensorFlow with TensorRT，后者我试过是可以的。2、可以将优化后的模型保存为pb，然后线上用CPP推理。通过实验，分类模型（inception_v3）FP16的QPS提升3倍。但是OCR模型，因为输入不固定，优化不成功。

**Comment by ZhuoranLyu** [comment]
@chong-lee Thanks, did you compile tftrt with bazel according to https://www.tensorflow.org/install/source_windows ? I did not see any tensorrt configuration on that page.

**Comment by chong-lee** [comment]
@ZhuoranLyu I compile tftrt with bazel according to [https://www.tensorflow.org/install/source](https://www.tensorflow.org/install/source).

**Comment by ZhuoranLyu** [comment]
@chong-lee BTW, did you compile for pip wheel or C++ API? If C++ API, did you compile this libtensorflow_cc.so file? May I ask for your QQ number because I have some questions about tftrt.

**Comment by chong-lee** [comment]
转tf-trt需要编译pip wheel，线上推理需要tensorflow动态库。


可以加我微信：bug_me_not





At 2019-08-15 17:08:05, "Zhuoran Lyu" <notifications@github.com> wrote:


@chong-lee BTW, did you compile for pip wheel or C++ API? If C++ API, did you compile this libtensorflow_cc.so file? May I ask for your QQ number because I have some questions about tftrt.

**Comment by MachineJeff** [comment]
@chong-lee 哥，线上推理 需要tensorflow 动态库 这是啥意思

**Comment by chong-lee** [comment]
> @chong-lee 哥，线上推理 需要tensorflow 动态库 这是啥意思

线上推理依赖支持tf-trt的tensorflow动态库

**Comment by SpriteLin-ZJU** [comment]
> 转tf-trt需要编译pip wheel，线上推理需要tensorflow动态库。

@chong-lee ,请问C++要使用tf-trt优化后的model，还是需要在python中先用tf-trt优化后的pb模型，然后线上推理用C++API像调用普通模型一样调用这个模型就好是嘛？我看https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html官网例子里说可以生成plan文件直接给tensorRT API调用，但是他这个生成的plan有很多个，不知道你了解怎么使用么

**Comment by chong-lee** [comment]
需要先用python的tf-trt转pb模型，转之后的模型，配合编译包含tensorrt的动态库，就像调用普通模型一样就好了。一般来说，FP16加速效果较好，且精度损失很小。

**Comment by chong-lee** [comment]
> > 转tf-trt需要编译pip wheel，线上推理需要tensorflow动态库。
> 
> @chong-lee ,请问C++要使用tf-trt优化后的model，还是需要在python中先用tf-trt优化后的pb模型，然后线上推理用C++API像调用普通模型一样调用这个模型就好是嘛？我看[https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html官网例子里说可以生成plan文件直接给tensorRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html%E5%AE%98%E7%BD%91%E4%BE%8B%E5%AD%90%E9%87%8C%E8%AF%B4%E5%8F%AF%E4%BB%A5%E7%94%9F%E6%88%90plan%E6%96%87%E4%BB%B6%E7%9B%B4%E6%8E%A5%E7%BB%99tensorRT) API调用，但是他这个生成的plan有很多个，不知道你了解怎么使用么

需要先用python的tf-trt转pb模型，转之后的模型，配合编译包含tensorrt的动态库，就像调用普通模型一样就好了。一般来说，FP16加速效果较好，且精度损失很小。

**Comment by haoshengup** [comment]
> > > 转tf-trt需要编译pip wheel，线上推理需要tensorflow动态库。
> > 
> > 
> > @chong-lee ,请问C++要使用tf-trt优化后的model，还是需要在python中先用tf-trt优化后的pb模型，然后线上推理用C++API像调用普通模型一样调用这个模型就好是嘛？我看[https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html官网例子里说可以生成plan文件直接给tensorRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html%E5%AE%98%E7%BD%91%E4%BE%8B%E5%AD%90%E9%87%8C%E8%AF%B4%E5%8F%AF%E4%BB%A5%E7%94%9F%E6%88%90plan%E6%96%87%E4%BB%B6%E7%9B%B4%E6%8E%A5%E7%BB%99tensorRT) API调用，但是他这个生成的plan有很多个，不知道你了解怎么使用么
> 
> 需要先用python的tf-trt转pb模型，转之后的模型，配合编译包含tensorrt的动态库，就像调用普通模型一样就好了。一般来说，FP16加速效果较好，且精度损失很小。

你好，请问你是在Windows还是Linux平台上使用的c++接口，我看到一些资料好像说Windows不支持tf-trt。

**Comment by chong-lee** [comment]
> > > > 转tf-trt需要编译pip wheel，线上推理需要tensorflow动态库。
> > > 
> > > 
> > > @chong-lee ,请问C++要使用tf-trt优化后的model，还是需要在python中先用tf-trt优化后的pb模型，然后线上推理用C++API像调用普通模型一样调用这个模型就好是嘛？我看[https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html官网例子里说可以生成plan文件直接给tensorRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html%E5%AE%98%E7%BD%91%E4%BE%8B%E5%AD%90%E9%87%8C%E8%AF%B4%E5%8F%AF%E4%BB%A5%E7%94%9F%E6%88%90plan%E6%96%87%E4%BB%B6%E7%9B%B4%E6%8E%A5%E7%BB%99tensorRT) API调用，但是他这个生成的plan有很多个，不知道你了解怎么使用么
> > 
> > 
> > 需要先用python的tf-trt转pb模型，转之后的模型，配合编译包含tensorrt的动态库，就像调用普通模型一样就好了。一般来说，FP16加速效果较好，且精度损失很小。
> 
> @chong-lee你好，请问你是在Windows还是Linux平台上使用的c++接口，我看到一些资料好像说Windows不支持tf-trt。

我是在Linux平台上，Windows没试过
